language: go

go:
  - 1.8
  - 1.7
  - master

go_import_path: collectd.org

matrix:
  allow_failures:
    - go: master

before_script:
  - go get github.com/golang/lint/golint

script:
  - go vet -x ./...
  - CGO_ENABLED=0 go test -v ./...

# TODO(octo): run the fuzz test:
# - go test -v -tags gofuzz ./...
